server.port=9037
spring.application.name=expensetrackerms


spring.datasource.url=jdbc:postgresql://localhost:5446/my_expense_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.hibernate.ddl-auto = update

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

#jwt token
spring.private.token=my_super_secret_key_123456_extra_characters_for_security

#logs
logging.level.org.springframework.security=DEBUG
logging.level.job_application_system_training_project=DEBUG





#1)
#docker run --name my-postgres-expensedb -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=my_expense_db -p 5446:5432 -d postgres  ---> for running the db container

#2) for entering the DB
#docker exec -it my-postgres-bb psql -U postgres -d my_booking_db